# $<Schema>$ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action workspace."
inputs:
  target:
    description: "{string[]} Target."
    required: false
    default: "./"
  deep:
    description: "{boolean} Scan deeper."
    required: false
    default: "false"
  clamav_enable:
    description: "{boolean} Use ClamAV."
    required: false
    default: "true"
  yara_enable:
    description: "{boolean} Use YARA."
    required: false
    default: "true"
  experiment_yara_excluderules:
    description: "{string[]} Exclude YARA rules."
    required: false
    default: |
      Loki Rules/apt_scanbox_deeppanda.yar
      Loki Rules/crime_malumpos.yar
      Loki Rules/general_cloaking.yar
      Loki Rules/thor_inverse_matches.yar
      Loki Rules/thor-hacktools.yar
      Loki Rules/thor-webshells.yar
  experiment_yara_warning:
    description: "{boolean} Enable YARA warning."
    required: false
    default: "false"
runs:
  using: "docker"
  image: "docker://ghcr.io/hugoalh/scan-virus-ghaction:0.5.0"
branding:
  icon: "shield"
  color: "red"
