# $<Schema>$ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action workspace."
inputs:
  targets:
    description: "{string[]} Targets."
    required: false
    default: "./"
  deep:
    description: "{boolean} Scan deeper."
    required: false
    default: "false"
  clamav_enable:
    description: "{boolean} Use ClamAV."
    required: false
    default: "true"
  yara_enable:
    description: "{boolean} Use YARA."
    required: false
    default: "false"
  yara_rulesfilter_list:
    description: "{string[]} YARA rules filter list."
    required: false
    default: ""
  yara_rulesfilter_mode:
    description: "{string} YARA rules filter mode."
    required: false
    default: "exclude"
  yara_warning:
    description: "{boolean} Enable YARA warning."
    required: false
    default: "false"
  target:
    description: "{string[]} Target."
    required: false
    default: "./"
    deprecationMessage: "Use `targets`!"
runs:
  using: "docker"
  image: "../Dockerfile"
branding:
  icon: "shield"
  color: "red"
