# $<Schema>$ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action workspace."
inputs:
  target:
    description: "{string} Target."
    required: false
    default: "./"
  cache:
    description: "{boolean} Cache data."
    required: false
    default: "false"
  deep:
    description: "{boolean} Scan deeper."
    required: false
    default: "false"
runs:
  using: "docker"
  image: "../Dockerfile"
branding:
  icon: "shield"
  color: "red"
