# $<Schema>$ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Scan Virus"
author: "hugoalh"
description: "Scan virus in the GitHub Action workspace."
inputs:
  integrate:
    description: "{string} Integrate with service."
    required: false
    default: "none"
  list_elements:
    description: "{(number | string)} List elements."
    required: false
    default: "none"
  list_elementshashes:
    description: "{boolean} List elements' hashes under itself."
    required: false
    default: "false"
  list_miscellaneousresults:
    description: "{(number | string)} List miscellaneous results."
    required: false
    default: "debug"
  list_scanresults:
    description: "{(number | string)} List scan results."
    required: false
    default: "debug"
runs:
  using: "docker"
  image: "../Dockerfile"
branding:
  icon: "shield"
  color: "red"
