# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  parse-content:
    name: "(Parse Content)"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          [string]$Content = @"
          Version ${{github.event.release.name}} (${{github.event.release.tag_name}}) is released and available on:
          
          - **GitHub (& Changelog):** ${{github.event.release.html_url}}
          - **GitHub Marketplace:** https://github.com/marketplace/actions/scan-virus
          - **Repository:** ${{github.event.repository.html_url}}
          "@
          Write-Host -Object "::set-output name=content::$Content"
        id: "parser"
        shell: "pwsh"
    outputs:
      content: "${{steps.parser.outputs.content}}"
  announce-new-release-discord:
    name: "Announce New Release - Discord"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-content"
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@v4.1.1"
        with:
          key: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_PROJECTNEWRELEASEANNOUNCER}}"
          payload: |
            {
              "embeds": [
                {
                  "description": "**__Scan Virus (GitHub Action)__**",
                  "color": "16,116,231",
                  "thumbnail": {
                    "url": "https://i.imgur.com/knmLbFg.png"
                  }
                }
              ]
            }
      - uses: "hugoalh/send-discord-webhook-ghaction@v4.1.1"
        with:
          key: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_PROJECTNEWRELEASEANNOUNCER}}"
          payload: |
            {
              "content": "${{needs.parse-content.outputs.content}}"
            }
