# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  parse-payload:
    name: "(Parse Payload)"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          function Format-GHActionsCommand {
            [CmdletBinding()][OutputType([string])]
            param(
              [Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)][AllowEmptyString()][Alias('Input', 'Object')][string]$InputObject,
              [switch]$Property
            )
            begin {}
            process {
              [string]$Result = $InputObject -replace '%', '%25' -replace "\n", '%0A' -replace "\r", '%0D'
              if ($Property) {
                $Result = $Result -replace ',', '%2C' -replace ':', '%3A'
              }
              return $Result
            }
            end {}
          }
          [string]$Header = @"
          **__Scan Virus (GitHub Action)__**

          ${{github.event.repository.description}}

          - ${{github.event.repository.html_url}}
          "@
          [string]$Content = @"
          Version ${{github.event.release.name}} (${{github.event.release.tag_name}}) is released and available on:
          
          - **GitHub Repository (& Changelog):** ${{github.event.release.html_url}}
          - **GitHub Marketplace:** https://github.com/marketplace/actions/scan-virus
          "@
          Write-Host -Object "::set-output name=header::$(Format-GHActionsCommand -InputObject $Header)"
          Write-Host -Object "::set-output name=content::$(Format-GHActionsCommand -InputObject $Content)"
        id: "parser"
        shell: "pwsh"
    outputs:
      header: "${{steps.parser.outputs.header}}"
      content: "${{steps.parser.outputs.content}}"
  announce-new-release-discord:
    name: "Announce New Release - Discord"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-payload"
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@v4.1.1"
        with:
          key: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_PROJECTNEWRELEASEANNOUNCER}}"
          payload: |
            {
              "embeds": [
                {
                  "description": "${{needs.parse-payload.outputs.header}}",
                  "color": "16,116,231",
                  "thumbnail": {
                    "url": "https://i.imgur.com/knmLbFg.png"
                  }
                }
              ]
            }
          wait: "true"
      - uses: "hugoalh/send-discord-webhook-ghaction@v4.1.1"
        with:
          key: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_PROJECTNEWRELEASEANNOUNCER}}"
          payload: |
            {
              "content": "${{needs.parse-payload.outputs.content}}"
            }
          wait: "true"
