# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Build Custom Environment"
on:
  schedule:
    - cron: "0 0 * * 3"
  push:
    branches:
      - "main"
  release:
    types:
      - "published"
env:
  IMAGE_NAME: "${{github.repository}}"
  REGISTRY: "ghcr.io"
jobs:
  build-custom-environment:
    name: "Build Custom Environment"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.4.0"
      - name: "Sign In To Registry ${{env.REGISTRY}}"
        uses: "docker/login-action@v1.10.0"
        with:
          registry: "${{env.REGISTRY}}"
          username: "${{github.actor}}"
          password: "${{github.token}}"
      - name: "Extract Docker Metadata"
        id: "meta"
        uses: "docker/metadata-action@v3.6.1"
        with:
          images: "${{env.REGISTRY}}/${{env.IMAGE_NAME}}"
      - name: "Build & Push Docker Image"
        uses: "docker/build-push-action@v2.7.0"
        with:
          file: "custom-environment/Dockerfile"
          labels: "${{steps.meta.outputs.labels}}"
          pull: "true"
          push: "true"
          tags: "${{steps.meta.outputs.tags}}"
