# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Scan Virus (Build)"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
    inputs:
      deep:
        description: "{boolean} Scan deeper."
        required: false
        default: "true"
      git_reversesession:
        description: "{boolean} Reverse Git session."
        required: false
        default: "false"
jobs:
  parse-inputs:
    name: "(Parse Inputs)"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          [string]$Deep = '${{github.event.inputs.deep}}'
          [string]$GitReverseSession = '${{github.event.inputs.git_reversesession}}'
          if ($Deep.Length -eq 0) {
            $Deep = 'false'
          }
          if ($GitReverseSession.Length -eq 0) {
            $GitReverseSession = 'false'
          }
          Write-Host -Object "::set-output name=deep::$Deep"
          Write-Host -Object "::set-output name=git_reversesession::$GitReverseSession"
        id: "parser"
        shell: "pwsh"
    outputs:
      deep: "${{steps.parser.outputs.deep}}"
      git_reversesession: "${{steps.parser.outputs.git_reversesession}}"
  scan-virus:
    name: "Scan Virus"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-inputs"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.1"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/use-docker-build@main"
        with:
          deep: "${{needs.parse-inputs.outputs.deep}}"
          git_reversesession: "${{needs.parse-inputs.outputs.git_reversesession}}"
          clamav_filesfilter_list: |
            ^yara-rules\/
            ^yara-rules$
          yara_enable: "true"
          yara_filesfilter_list: |
            ^\.git\/
            ^\.git$
            ^yara-rules\/
            ^yara-rules$
          yara_rulesfilter_list: |
            ^blacktop\/peertopeer>Dockerfile$
            ^yara-community\/capabilities\/spreading_file>\.gitignore$
            ^yara-community\/maldocs\/powershell>\.github\/workflows\/scan-virus-build\.yml$
            ^yara-community\/maldocs\/powershell>\.github\/workflows\/scan-virus\.yml$
            ^yara-community\/maldocs\/powershell>Dockerfile$
            ^yara-community\/maldocs\/powershell>README\.md$
          yara_warning: "true"
