# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Scan Virus"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
    inputs:
      integrate_git:
        description: "{boolean} Git integration."
        required: false
        default: "true"
jobs:
  depth:
    name: "Depth Scan"
    runs-on: "ubuntu-latest"
    if: "${{github.event.inputs.integrate_git == 'true'}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.4.0"
        with:
          fetch-depth: 0
      - name: "Depth Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/use-docker-build@main"
        with:
          integrate: "git"
          list_elements: "debug"
          list_elementshashes: "debug"
  flat:
    name: "Flat Scan"
    runs-on: "ubuntu-latest"
    if: "${{github.event.inputs.integrate_git != 'true'}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.4.0"
      - name: "Flat Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/use-docker-build@main"
        with:
          list_elements: "debug"
          list_elementshashes: "debug"
