# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Scan Virus - Cross"
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
concurrency:
  group: "scan-virus-cross"
jobs:
  scan-virus-cross:
    name: "${{matrix.repositories}}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        repositories:
          - "0x48piraj/MalWAReX"
          - "acastillorobles77/MalwareDatabase"
          - "CYB3RMX/MalwareAnalysis101"
          - "Da2dalus/The-MALWARE-Repo"
          - "desktop/desktop"
          - "electron/electron"
          - "Endermanch/MalwareDatabase"
          - "fabrimagic72/malware-samples"
          - "facebook/react"
          - "HynekPetrak/javascript-malware-collection"
          - "InQuest/malware-samples"
          - "jstrosch/malware-samples"
          - "MalDev101/Loveware"
          - "MalwareSamples/Linux-Malware-Samples"
          - "MalwareSamples/Macos-Malware-Samples"
          - "MalwareSamples/Ransomware-Malware-Samples"
          - "mstfknn/malware-sample-library"
          - "NavyTitanium/Misc-Malwares"
          - "NEUAI/MalwareLibrary"
          - "npm/cli"
          - "PowerShell/PowerShell"
          - "Virus-Samples/Malware-Sample-Sources"
      fail-fast: false
      max-parallel: 2
    steps:
      - name: "Checkout Repository ${{matrix.repositories}}"
        uses: "actions/checkout@v2.4.0"
        with:
          repository: "${{matrix.repositories}}"
          fetch-depth: 0
          token: "${{secrets.GHP_SCANVIRUSCLONEREPOSITORY}}"
      - name: "Depth Scan Repository ${{matrix.repositories}}"
        uses: "hugoalh/scan-virus-ghaction@v0.3.2"
        with:
          gitdepth: "true"
          list_elements: "none"
          list_elementshashes: "none"
          list_miscellaneousresults: "none"
          list_scanresults: "none"
