# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Scan Virus - Cross"
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
concurrency:
  group: "scan-virus-cross"
jobs:
  scan-virus-cross:
    name: "${{matrix.repositories}}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        repositories:
          - "0x48piraj/MalWAReX"
          - "acastillorobles77/MalwareDatabase"
          - "actions/runner"
          - "actions/toolkit"
          - "actions/virtual-environments"
          - "Ajaxy/telegram-tt"
          - "ajv-validator/ajv"
          - "CYB3RMX/MalwareAnalysis101"
          - "Da2dalus/The-MALWARE-Repo"
          - "denoland/deno"
          - "desktop/desktop"
          - "DrKLO/Telegram"
          - "electron/electron"
          - "Endermanch/MalwareDatabase"
          - "enquirer/enquirer"
          - "evgeny-nadymov/telegram-react"
          - "evgeny-nadymov/telegram-wp"
          - "fabrimagic72/malware-samples"
          - "facebook/react"
          - "git-for-windows/git"
          - "git/git"
          - "github/tweetsodium"
          - "godotengine/godot"
          - "HynekPetrak/javascript-malware-collection"
          - "InQuest/malware-samples"
          - "iptv-org/iptv"
          - "jekyll/jekyll"
          - "jmespath/jmespath.js"
          - "jstrosch/malware-samples"
          - "M66B/NetGuard"
          - "MalDev101/Loveware"
          - "MalwareSamples/Linux-Malware-Samples"
          - "MalwareSamples/Macos-Malware-Samples"
          - "MalwareSamples/Ransomware-Malware-Samples"
          - "microsoft/PowerToys"
          - "microsoft/vscode"
          - "misode/misode.github.io"
          - "morethanwords/tweb"
          - "mstfknn/malware-sample-library"
          - "NavyTitanium/Misc-Malwares"
          - "NEUAI/MalwareLibrary"
          - "node-fetch/node-fetch"
          - "nodejs/node"
          - "notepad-plus-plus/notepad-plus-plus"
          - "npm/cli"
          - "nuno-faria/tiler"
          - "obsproject/obs-studio"
          - "octalmage/robotjs"
          - "OpenNBS/OpenNoteBlockStudio"
          - "overtake/TelegramSwift"
          - "PowerShell/PowerShell"
          - "qbittorrent/qBittorrent"
          - "Querz/mcaselector"
          - "rcmaehl/WhyNotWin11"
          - "simple-icons/simple-icons"
          - "spotify/pedalboard"
          - "tdlib/td"
          - "telegramdesktop/tdesktop"
          - "TelegramMessenger/Telegram-iOS"
          - "tobspr/shapez.io"
          - "twitter/twemoji"
          - "Virus-Samples/Malware-Sample-Sources"
          - "zhukov/webogram"
      fail-fast: false
      max-parallel: 2
    steps:
      - name: "Checkout Repository ${{matrix.repositories}}"
        uses: "actions/checkout@v2.4.0"
        with:
          repository: "${{matrix.repositories}}"
          fetch-depth: 0
          token: "${{secrets.GHP_SCANVIRUSCLONEREPOSITORY}}"
      - name: "Depth Scan Repository ${{matrix.repositories}}"
        uses: "hugoalh/scan-virus-ghaction@v0.3.2"
        with:
          gitdepth: "true"
          list_elements: "none"
          list_elementshashes: "none"
          list_miscellaneousresults: "none"
          list_scanresults: "none"
