# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Scan Virus - Specify Repositories"
on:
  workflow_dispatch:
    inputs:
      repositories:
        description: "{string[]} GitHub repositories."
        required: true
jobs:
  parse-inputs:
    name: "Parse Inputs"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          $Repositories = '${{github.event.inputs.repositories}}'.Trim() -split '[ ,;]+'
          for ($Index = 0; $Index -lt $Repositories.Count; $Index++) {
            $Repositories[$Index] = $Repositories[$Index] -replace '^(?:https?:\/\/)?github\.com\/', ''
          }
          Write-Host -Object "::set-output name=matrix::{`"repositories`":[`"$($Repositories -join '","')`"]}"
        id: "parser"
        shell: "pwsh"
    outputs:
      matrix: "${{steps.parser.outputs.matrix}}"
  scan-virus-specify-repositories:
    name: "${{matrix.repositories}}"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-inputs"
    strategy:
      fail-fast: false
      matrix: "${{fromJSON(needs.parse-inputs.outputs.matrix)}}"
    steps:
      - name: "Checkout Repository ${{matrix.repositories}}"
        uses: "actions/checkout@v2.4.0"
        with:
          repository: "${{matrix.repositories}}"
          fetch-depth: 0
          token: "${{secrets.GHP_SCANVIRUSCLONEREPOSITORY}}"
      - name: "Depth Scan Repository ${{matrix.repositories}}"
        uses: "hugoalh/scan-virus-ghaction@main"
        with:
          integrate: "git"
          list_miscellaneousresults: "none"
          list_scanresults: "none"
